using System.Collections.Generic;
using System.Data.SqlClient;
using BrainWare.Dal.Models;
using Dapper;

namespace BrainWare.Dal
{
    
    
    public class OrderRepository
    {
        // Create a method called GetOrdersForCompany that returns a list of orders for a given company id
        // The list should include the order id, the company name and the order description
        // The method should use dapper to execute the sql
        // The sql should use a join to get the company name from the company table
        //the sql should be generated by the sql builder dapper library
        
        public IEnumerable<Order> GetCompanyOrders(int companyId)
        {
            using (var con = new SqlConnection("Data Source=localhost;Initial Catalog=BrainWAre;Integrated Security=SSPI;"))
            {
                var builder = new SqlBuilder();
                var template = builder.AddTemplate(
                    @"select o.order_id as [OrderId], c.name as [CompanyName], o.description 
                        FROM company c INNER JOIN [order] o on c.company_id=o.company_id /**where**/");

                builder.Where("o.company_Id = @CompanyId", new { CompanyId = companyId });

                return con.Query<Order>(template.RawSql, template.Parameters);
            }   
        }
        
        
        
         
    }
}